name: mymap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  cloud_firestore: ^3.5.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  location_picker_flutter_map: ^1.0.3
  get: 4.6.5
  flutter: 
    sdk: flutter

dependency_overrides:
  flutter_platform_widgets: ^2.0.0
   

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

